### ISSUE TITLE
[1.12] [Compatibility Suggestion] Additional Support Suggestions

### ISSUE THREAD

**Issue by DShou** [blay09/KleethoMod#11]
Suggestion List:
- [x] Binnie's Mods
- [x] ~~Natura~~
- [x] Quark [Partial, some slabs not supported]
- [x] ~~Tinker's Construct~~

I understand Immersive Engineering is non-standard, and would understand issues would arise if any of these mods had non-standard slabs as well.

**Comment by BlayTheNinth** [comment]
Sadly, Natura and Tinker's Construct slabs become real full blocks once two slabs have been stacked on top each other (as opposed to the usual 'double slab block'), meaning there is no way to differentiate between slabs and real blocks anymore, making support impossible.

Support for Extra Trees is coming in the next version.
