### ISSUE TITLE
Cross-mod interaction with Thermal Foundation Hammers

### ISSUE THREAD

**Issue by Serifina** [blay09/KleethoMod#16]
The new versions (both 5.4.6 and 5.4.7) have a weird interaction with Thermal Foundation hammers. In Creative mode only, the hammers break the 3x3 area, and then the broken blocks are immediately replaced with Botania Sunny Quartz slabs, as if you were trying to break just one slab in a double slab. Version 5.3.2 does not cause this, nor does it happen in Survival, and I haven't found any of the other area-mine tools that it happens with.

**Comment by walker-dev** [comment]
#15 same happend here, update to 5.4.7 still does the same

**Comment by orbwoi** [comment]
I get this in survival with the Actually Additions Drill with 3x3 upgrade in Survival.
Any 'air' blocks are replaced in the 3x3 are replaced by Botania Sunny Quartz slabs.
(This happens 100% of the time)

I was forced to remove the mod from my pack because it made drills unusable.
