### ISSUE TITLE
Stone Slabs Broken with Hand Aren't Destroyed

### ISSUE THREAD

**Issue by kiwifails** [blay09/KleethoMod#2]
Basically the title. I added the mod to my Project Ozone instance and experienced this with cobblestone slabs. Here's the stream VOD with the proper timestamp http://www.twitch.tv/kiwifails/v/46622806?t=20m24s

If this was sneak-updated in the last version apologies, didn't see it on the changelog (:

**Comment by blay09** [comment]
Thanks! It'll be fixed in the next version.
