### ISSUE TITLE
Crash on joining World

### ISSUE THREAD

**Issue by NielsPilgaard** [blay09/KleethoMod#25]
Hey, I crashed while trying to join a newly made world, here's the log: 
https://gist.github.com/NillerMedDild/b185b4c046c9441d4df3e2bc72115d4d

`KleeSlabs_1.14.2-7.4.3`

**Comment by BlayTheNinth** [comment]
The 1.14.2 version is not compatible with 1.14.3. A port for 1.14.3 has been released.

**Comment by NielsPilgaard** [comment]
Ah okay, thanks.
