### ISSUE TITLE
[Suggestion] Add support for shift-mining entire block

### ISSUE THREAD

**Issue by GreatestFool** [blay09/KleethoMod#28]
Couldn't really think of a good title, sorry.

Can you add support for shift-mining (or something similar) whole slab blocks? I like this mod and it makes life easier when you need to mine one slab at a time, but inversely, when you need to mine the entire block you have to mine both slabs individually. I think it sounds like a good addition to the mod, but I don't know if it's possible to add this code-wise. I thought I'd ask at least. Sorry if this isn't how/where you're supposed to suggest features.

**Comment by BlayTheNinth** [comment]
You can enable `requireSneak` and `invertSneak` in the config to get the desired behaviour.

**Comment by GreatestFool** [comment]
Oh, TIL I guess. Sorry for the disturbance and thanks for the help :)
