### ISSUE TITLE
[Please Close] Crash when looking at generated slabs in a village.

### ISSUE THREAD

**Issue by ChloeDawn** [blay09/KleethoMod#3]
Game crashed when entering a village in a single player world and looking at double stone slabs generated in the blacksmith building.

EDIT: I realise in your commits it appears that this is fixed, but I wasn't sure if this was a different issue, since the upload date for the file on CurseForge is more recent than the commits date.

**EDIT 2: Please ignore this and just close it. I was stupid. I'm using the 1.9.4 version somehow? I don't even know how I managed that. I'm a fucking mess. Sorry.**

**Minecraft version:** 1.10.2
**Forge version:** 12.18.0.2010
**Mod version:** [3.3.1](http://minecraft.curseforge.com/projects/kleeslabs/files/2309737)

**Stacktrace:**

> ```
> at net.blay09.mods.kleeslabs.KleeSlabs.onDrawBlockHighlight(KleeSlabs.java:158)
> at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_293_KleeSlabs_onDrawBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
> at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68)
> at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159)
> at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:158)
> at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1329)
> at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
> ```

**Full crash report:** [pastebin.com/rDkcgnwd](http://pastebin.com/rDkcgnwd)

**Comment by BlayTheNinth** [comment]
No worries :)
