### ISSUE TITLE
[Compatibility] Double Slabs breaks Klee

### ISSUE THREAD

**Issue by ghost** [blay09/KleethoMod#33]
[KleeSlabs_1.14.4-7.4.8.jar](https://www.curseforge.com/minecraft/mc-mods/kleeslabs/files/2850745) breaks with [DoubleSlabs-1.14-1.2.7](https://www.curseforge.com/minecraft/mc-mods/double-slabs/files/2949832)

Klee appears to completely break in the presence of DoubleSlabs, though the hitbox for a full block appears on the bottom of a slab
![sqr issue pic](https://user-images.githubusercontent.com/32821049/81473819-8afef580-91be-11ea-9253-99852ac48e92.png)

**Comment by BlayTheNinth** [comment]
I think this was a general KleeSlabs issue fixed in #46
