### ISSUE TITLE
Create mod compatibility

### ISSUE THREAD

**Issue by Barerock** [blay09/KleethoMod#35]
The sideways slabs (and other orientations) aren't compatible with moving constructs in Create. Rotating bearings for example cause non-normal slabs to become pink/black no texture blocks. Quark doesn't have this problem with their sideways slabs, so maybe contact Vazkii for pointers on how to keep the texture there? Thanks!

I also posted this on the Create forum.

**Comment by BlayTheNinth** [comment]
KleeSlabs doesn't add any sideway-slabs, KleeSlabs only allows you to break a single half of a normal double slab

**Comment by Barerock** [comment]
I've gotten something mixed up then
Let me look at my load order and close this.
