### ISSUE TITLE
BetterMC collection not working with mod

### ISSUE THREAD

**Issue by DEMEMZEA** [blay09/KleethoMod#74]
### Minecraft Version

1.19.2 (LTS)

### Mod Loader

Fabric

### Mod Loader Version

0.14.21

### Mod Version

12.3.0

### Balm Version

Sorry, what is balm?

### Describe the Issue

I was playing BetterMC ( Fabric ) ( the modpack ) when i noticed that your mod does not work with the collection enchantment there ( I would have reported the bug there if i knew what was the name of the mod that adds this enchantment ), and the slab did not go to my inventory ( which is what should have happened ).

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

I use the BetterMC Modpack

**Comment by BlayTheNinth** [comment]
What mod adds the Collection enchantment?
