### ISSUE TITLE
Bottom slab breaking instead of top when breaking top slab

### ISSUE THREAD

**Issue by NezzleGod** [blay09/KleethoMod#76]
### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Mod Loader Version

0.14.21

### Mod Version

15.0.0

### Balm Version

7.0.2.

### Describe the Issue

When breaking the top slab, only the lower half breaks.

Here is a video link - https://youtu.be/uKbG4vCYTHE

**Comment by BlayTheNinth** [comment]
Fixed in Balm 7.0.3
