### ISSUE TITLE
Doesn't work with modded slabs

### ISSUE THREAD

**Issue by vinnyg0621** [blay09/KleethoMod#82]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Forge

### Mod Loader Version

47.3.1

### Mod Version

15.0.0

### Balm Version

7.3.4

### Describe the Issue

when I click on a double modded slab, it mines the whole block.

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

yes I use optifine

**Comment by BlayTheNinth** [comment]
KleeSlabs uses datapacks to define what slabs it works on. Without knowing what "modded slab" it is, there's nothing I can do.

**Comment by vinnyg0621** [comment]
I don't know how to create a datapack for this mod.

**Comment by BlayTheNinth** [comment]
I don't know what modded slab you're referring to because you provided no information in your issue report.

**Comment by vinnyg0621** [comment]
> KleeSlabs uses datapacks to define what slabs it works on. Without knowing what "modded slab" it is, there's nothing I can do.

oh rly? i thought it supported all slabs...
